### PR TITLE
Added kresd as local nameserver so rspamd stops complaining

### PR DESCRIPTION
**Pull request by phdoerfler**
Kudos to @erosennin for suggesting this!
Hopefully this fixes https://github.com/r-raymond/nixos-mailserver/issues/52.

### CODE REVIEW

**Comment by phdoerfler** [comment]
On my system this does indeed fix #52. However for reasons outlined in #52 applying this PR would break nixos-mailserver on NixOS's running a stable channel.

**Comment by r-raymond** [comment]
Is this problem (mentioned in #52) a problem of kresd or all nameservers on Nixos?

Otherwise we could try unbound [(recommended by rspamd)](https://rspamd.com/doc/faq.html#resolver-setup) instead

**Comment by jbboehr** [comment]
Should be backported to 17.09 now: https://github.com/NixOS/nixpkgs/commit/f705efa34c6400f4d343ea905e6cad6cd52aa23b

Although I'm using unbound for some other stuff now, so it would not work with my setup. Should we perhaps put unbound/kresd behind a flag?

TBH since it's literally two static lines of configuration should unbound/kresd even be included by default?

**Comment by r-raymond** [comment]
Great, can someone confirm if it works on 17.09? Then I'll pull the changes

@jbboehr Isn't that the way the @phdoerfler implemented it? What would you change?

**Comment by jbboehr** [comment]
My apologies, it appears I had been referencing the existing code.

**Pull request merged**
