### PR TITLE
Support for multiple extraVirtualAliases

### LINKED ISSUE #104: How to send email to multiple recipients
How do you send email to multiple virtual accounts?

ie office@domain goes to account1@domain and account2@domain?

Adding office@domain to each of the accounts aliases attribute results in mail only being sent to one of the accounts

### PR DESCRIPTION
**Pull request by geistesk**
Should fix #104 by introducing

```
extraVirtualAliases = {
  "single-alias@domain.foobar" = "user1@domain.foobar";
  "multi-alias@domain.foobar" = [
    "user1@domain.foobar" "user2@domain.foobar" ];
};
```

### CODE REVIEW

**Comment by r-raymond** [comment]
awesome, thanks for the hard work!

If you find some time, can you add a test for this feature? If not, I'll try to find some. Thanks!

**Comment by geistesk** [comment]
I have to admit that I'm not so familiar with the Nix tests, but I would try it later on this evening.

**Comment by geistesk** [comment]
So, I updated the PR and added tests in `tests/extern.nix`.

Btw, I've got the diff running successfully *in production* since opening the PR and *it works on my machine*. For what it's worth.

**Comment by r-raymond** [comment]
Awesome! Thanks again!

**Pull request merged**
