### PR TITLE
Don't include identity twice in vaccounts

### LINKED ISSUE #94: Duplicate entries in vaccounts
#### SNM Version: (e.g. v2.1.3)
v2.1.3
#### Nixos Version: (e.g. 17.09 or unstable)
unstable

#### Relevant part of the config to reproduce:
I have set `fqdn`, `domains` and `loginAccounts`. Some of the `loginAccounts` have `aliases`.

#### What happened:
The file `/var/lib/postfix/conf/vaccounts` contains the lines that do not represent aliases twice.

#### Relevant journald log:
```
postfix-pre-start[12408]: postmap: warning: /var/lib/postfix/conf/vaccounts.db: duplicate entry: "mail@example.com"
postfix/postmap[12451]: warning: /var/lib/postfix/conf/vaccounts.db: duplicate entry: "mail@example.com"
```

### PR DESCRIPTION
**Pull request by dotlambda**
fixes #94 

I wasn't able to test the changes to `extern.nix` because of #95.

### CODE REVIEW

**Comment by dotlambda** [comment]
From https://travis-ci.org/r-raymond/nixos-mailserver/requests:
> Abuse detected

???

**Comment by dotlambda** [comment]
Travis keeps complaining about abuse. However, I can confirm that the tests run locally using a checkout of the 17.09 channel.

**Comment by dotlambda** [comment]
@r-raymond Did you have a look at this?

**Comment by r-raymond** [comment]
@dotlambda  at the abuse alert? I have no idea where that is comming from.

**Comment by dotlambda** [comment]
@r-raymond At the PR.

**Comment by r-raymond** [comment]
Seems to be all good. Thanks for the PR!

**Pull request merged**
