### PR TITLE
Allow null host prefix

### LINKED ISSUE #11: Allow possibility to not use a hostPrefix
Testing mailing with [mail-tester.com](https://www.mail-tester.com/) I get the following warning:

> Your reverse DNS does not match with your sending domain.
> Reverse DNS lookup or reverse DNS resolution (rDNS) is the determination of a domain name that is associated with a given IP address.
> Some companies such as AOL will reject any message sent from a server without rDNS, so you must ensure that you have one.
> **You cannot associate more than one domain name with a single IP address.**

This is because my reverse DNS resolves to example.com, but the mail was sent from mail.example.com. Apparently some services like AOL take offence to that and treat mail as spam or bounce it.

Whilst it is neat to have a mail.example.com, it would require having multiple IP addresses to work correctly with mail providers, one for the TLD and one for each subdomain. At least according to mail-tester.com. Please 

However, simply using `hostPrefix = "";` results in a bunch of errors relating to `.example.com` not being a valid domain.

The most feasible thing might be to use a lib.optional to make the hostPrefix optional for those who are worried about their reverse DNS.

Thoughts?

### PR DESCRIPTION
**Pull request by eqyiel**
Closes #11, this is also something that I needed.

### CODE REVIEW

**Comment by r-raymond** [comment]
Great! I think though we should simply let the user specify the `fqdn`. I.e. remove the whole `hostPrefix` and `domain` part and let the user just specify whatever he wants. Also

```
smtpd_banner = $myhostname ESMTP NO UCE
```

in `postfix.nix` needs to be fixed. ($myhostname -> ${fqdn}) if the hostname is not used anymore

**Comment by eqyiel** [comment]
@r-raymond thanks for the review, I'm working on it, a couple questions though:

Should we still keep `domain` as a thing distinct from `fqdn`?  I think it's probably necessary right?

I mean otherwise stuff like this might not work:

```
valiases_postfix = map
    (from:
      let to = cfg.virtualAliases.${from};
      in "${from}@${cfg.domain} ${to}@${cfg.domain}")
    (builtins.attrNames cfg.virtualAliases);
```

This is a bit tied up with the multiple domains support as well.

I can imagine having a configuration option `mailserver.fqdn` as well as `mailserver.domains`, is this the direction you had in mind?

**Comment by r-raymond** [comment]
> I can imagine having a configuration option mailserver.fqdn as well as mailserver.domains, is this the direction you had in mind?

Exactly, we are trying to realize that right now in #22. But we could have a `v1.0` version with mailserver.fqdn and mailserver.domain as you mentioned.

**Comment by r-raymond** [comment]
Ok, now that multiple domains has landed, we have exactly this (mailserver.fqdn and mailserver.domains). Does that solve your usecase too?

**Comment by eqyiel** [comment]
@r-raymond yeah, #22 does all of this and more.

**Pull request closed without merging**
